# Generated by Django 3.2.8 on 2021-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_field', models.CharField(max_length=100)),
                ('superident', models.CharField(max_length=100)),
            ],
        ),
    ]
