# Generated by Django 3.2.8 on 2021-10-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='section',
            new_name='sec',
        ),
    ]
