# Generated by Django 3.2.6 on 2021-12-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagery',
            new_name='catag',
        ),
    ]
