# Generated by Django 3.2.6 on 2021-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_catagery_product_catag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/images', verbose_name=''),
        ),
    ]
