# Generated by Django 3.2.6 on 2021-12-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
