# Generated by Django 3.2.6 on 2022-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211227_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('email', models.IntegerField()),
                ('image', models.ImageField(upload_to='students/image')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
