# Generated by Django 4.0.3 on 2022-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('cnic', models.BigIntegerField()),
                ('ph1', models.BigIntegerField()),
                ('ph2', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('marital_status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='students/image')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
