# Generated by Django 3.2.8 on 2022-04-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=3)),
                ('organ_doner', models.CharField(max_length=10)),
                ('disability', models.CharField(max_length=10)),
                ('fitness', models.CharField(max_length=10)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.employee')),
            ],
            options={
                'db_table': 'emp_medical',
            },
        ),
    ]
