# Generated by Django 4.0.3 on 2022-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_emp_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('reg', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3)),
                ('batch', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='student/image')),
            ],
            options={
                'db_table': 'reg',
            },
        ),
    ]
