# Generated by Django 4.0.3 on 2022-04-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
