# Generated by Django 4.0.3 on 2022-04-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reg',
            new_name='reg_no',
        ),
    ]
