# Generated by Django 4.0.3 on 2022-04-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_reg_student_reg_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='stu',
        ),
        migrations.AlterModelTable(
            name='stu',
            table='stu',
        ),
    ]
