# Generated by Django 4.0.3 on 2022-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_student_stu_alter_stu_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stu',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
