# Generated by Django 4.0.3 on 2022-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_stu_batch_alter_stu_date_alter_stu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='image',
            field=models.BinaryField(),
        ),
    ]
