# Generated by Django 4.0.3 on 2022-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_courses',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=10)),
                ('date_of_complition', models.DateField()),
                ('certificate', models.CharField(max_length=50)),
                ('no_of_project', models.IntegerField()),
            ],
            options={
                'db_table': 'emp_courses',
            },
        ),
        migrations.CreateModel(
            name='emp_education',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=10)),
                ('year_of_passing', models.IntegerField()),
                ('persentage', models.IntegerField()),
                ('t_marks', models.IntegerField()),
                ('o_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'emp_education',
            },
        ),
        migrations.CreateModel(
            name='emp_emergency',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('ph1', models.BigIntegerField()),
                ('ph2', models.BigIntegerField()),
            ],
            options={
                'db_table': 'emp_emergency',
            },
        ),
        migrations.CreateModel(
            name='emp_experience',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
            ],
            options={
                'db_table': 'emp_experience',
            },
        ),
        migrations.CreateModel(
            name='emp_job',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('duty_time', models.IntegerField()),
            ],
            options={
                'db_table': 'emp_job',
            },
        ),
        migrations.CreateModel(
            name='emp_medical',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('blood', models.CharField(max_length=3)),
                ('organ_doner', models.CharField(max_length=10)),
                ('disability', models.CharField(max_length=10)),
                ('fitness', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'emp_medical',
            },
        ),
        migrations.CreateModel(
            name='emp_personal',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('cnic', models.BigIntegerField()),
                ('ph1', models.BigIntegerField()),
                ('ph2', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('marital_status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='employee/image')),
            ],
            options={
                'db_table': 'emp_personal',
            },
        ),
    ]
