# Generated by Django 4.0.3 on 2022-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_emp_courses_emp_education_emp_emergency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Vehicle',
            fields=[
                ('vehicleid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('engine_no', models.IntegerField(max_length=30)),
                ('body_no', models.IntegerField(max_length=40)),
                ('engine_pwr', models.IntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('capsity', models.IntegerField(max_length=30)),
                ('date1', models.DateField()),
            ],
            options={
                'db_table': 'Register_Vehicle',
            },
        ),
    ]
