# Generated by Django 4.0.3 on 2022-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_register_vehicle_engine_pwr'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=50)),
                ('v_id', models.CharField(max_length=20)),
                ('routes', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('stop', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
