# Generated by Django 4.0.3 on 2022-05-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='ewr',
            field=models.CharField(max_length=30),
        ),
    ]
