# Generated by Django 4.0.3 on 2022-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_routte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routte',
            name='cname',
            field=models.CharField(max_length=100),
        ),
    ]
