# Generated by Django 4.0.3 on 2022-05-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_routte_cname'),
    ]

    operations = [
        migrations.CreateModel(
            name='stop',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('rname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.AlterField(
            model_name='register_vehicle',
            name='body_no',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='register_vehicle',
            name='capsity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register_vehicle',
            name='engine_no',
            field=models.CharField(max_length=30),
        ),
    ]
