# Generated by Django 4.0.3 on 2022-05-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_stop_alter_register_vehicle_body_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_personal',
            name='designation',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
