# Generated by Django 4.0.3 on 2022-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_emp_personal_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
